# Re-Centris Configuration

# Path configurations
paths:
  repo_path: "./repos"
  tag_date_path: "./data/repo_date"
  result_path: "./data/repo_functions"

# Performance settings
performance:
  max_workers: 0  # 0 means use number of CPU cores
  cache_size: 1000
  memory_limit: 0.8  # Maximum memory usage (80%)

# Language settings
languages:
  cpp:
    enabled: true
    extensions:
      - ".c"
      - ".cc"
      - ".cpp"
      - ".cxx"
      - ".h"
      - ".hpp"
  java:
    enabled: false
    extensions:
      - ".java"
  python:
    enabled: false
    extensions:
      - ".py"

# Clone settings
clone:
  output: "./repos"
  workers: 5

# Analysis settings
analyze:
  output: "./analysis"
  workers: 5

# Detection settings
detect:
  known_files: "./known-files"
  output: "detection-results.json"
  workers: 5
  threshold: 0.8  # Similarity threshold (0.0-1.0) 